steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "verify"]
    dir: "/workspace/"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "genereraDemo",
        "--trigger-http",
        "--runtime",
        "java11",
        "--entry-point",
        "com.functions",
      ]
    dir: "/workspace/"
