steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "verify"]
    dir: "/workspace/"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "genereraDemo",
        "--trigger-http",
        "--region",
        "europe-west1",
        "--runtime",
        "java11",
        "--entry-point",
        "com.functions.HelloWorld",
      ]
    dir: "/workspace/"
    steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args: [./trigger.sh]
 
