steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "verify"]
    dir: "/workspace/"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "genereraDemo",
        "--trigger-http",
        "--runtime",
        "java11",
        "--entry-point",
        "com.functions.HelloWorld",
      ]
    dir: "/workspace/"
  - name: "node"
    env:
      - "URL=${_MY_DEPLOYED_URL}"
    args: ["run", "test:system"]
    dir: "/workspace/"
